using System;
using System.Collections.ObjectModel;
using SenseNet.ContentRepository;
using SenseNet.ContentRepository.Fields;
using SenseNet.ContentRepository.Schema;
using SenseNet.ContentRepository.Search.Indexing;

// ReSharper disable once CheckNamespace
namespace SenseNet.Search
{
    /// <summary>
    /// Define an inherited <see cref="Field"/> for manafing texte extractor list in the IndexingSettings.
    /// </summary>
    [ShortName("TextExtractors")]
    [DataSlot(0, RepositoryDataType.NotDefined, typeof(ReadOnlyDictionary<string, ITextExtractor>))]
    [DefaultFieldSetting(typeof(NullFieldSetting))]
    [DefaultFieldControl("SenseNet.Portal.UI.Controls.ShortText")]
    public class TextExtractorsField : Field
    {
        /// <summary>
        /// Overridden importer method. Not supported in this field because it has autogeneratd value.
        /// </summary>
        protected override void ImportData(System.Xml.XmlNode fieldNode, ImportContext context)
        {
            throw new NotSupportedException("The ImportData operation is not supported on TextExtractorsField.");
        }

        /// <summary>
        /// Overridden exporter method. Does nothing in this field because it has autogeneratd value.
        /// </summary>
        protected override void ExportData(System.Xml.XmlWriter writer, ExportContext context)
        {
            // do not export this field, it is autogenerated in the content handler.
        }
    }
}
