
services:
  sensenet-insql-cdb-snsql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sensenet-insql-cdb-snsql
    networks:
      - snnetwork
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuP3rS3CuR3P4sSw0Rd
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True
    healthcheck:
      test: >
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "
        IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = 'sensenet-insql-cdb-sndb')
          RAISERROR('Database missing', 16, 1)
        " || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "1433:1433"
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools
    networks:
      - snnetwork
    depends_on:
      - sensenet-insql-cdb-snsql
    command: >
      bash -c "
      echo 'Waiting for SQL Server to be ready...';
      until /opt/mssql-tools/bin/sqlcmd -S sensenet-insql-cdb-snsql -U SA -P 'SuP3rS3CuR3P4sSw0Rd' -Q 'SELECT 1'; do
        sleep 1;
      done;
      echo 'Creating database...';
      /opt/mssql-tools/bin/sqlcmd -S sensenet-insql-cdb-snsql -U SA -P 'SuP3rS3CuR3P4sSw0Rd' -Q 'CREATE DATABASE [sensenet-insql-cdb-sndb]';
      echo 'Database created successfully';
      "

  sensenet-insql-cdb-snis:
    image: sensenetcsp/sn-identityserver
    container_name: sensenet-insql-cdb-snis
    networks:
      - snnetwork
    depends_on:
      - db-init
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - sensenet__LoginPage__DisplayOtherRepositoryButton=true
      - sensenet__authentication__setDefaultClients=true
      - IdentityServer__IssuerUri=https://localhost:51017
      - sensenet__Clients__adminui__RepositoryHosts__0__PublicHost=https://localhost:51016
      - sensenet__Clients__spa__RepositoryHosts__0__PublicHost=https://localhost:51016
      - sensenet__Clients__client__RepositoryHosts__0__PublicHost=https://localhost:51016
      - sensenet__Clients__adminui__RepositoryHosts__0__InternalHost=http://sensenet-insql-cdb-snapp
      - sensenet__Clients__spa__RepositoryHosts__0__InternalHost=http://sensenet-insql-cdb-snapp
      - sensenet__Clients__client__RepositoryHosts__0__InternalHost=http://sensenet-insql-cdb-snapp
      - Kestrel__Certificates__Default__Path=/root/.aspnet/https/snapp.pfx
      - Kestrel__Certificates__Default__Password=SuP3rS3CuR3P4sSw0Rd
    volumes:
      - ./temp/certificates:/root/.aspnet/https:ro
    ports:
      - "51017:443"
    restart: always

  sensenet-insql-cdb-snapp:
    image: sensenetcsp/sn-api-sql
    container_name: sensenet-insql-cdb-snapp
    networks:
      - snnetwork
    depends_on:
      sensenet-insql-cdb-snsql:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - sensenet__Container__Name=sensenet-insql-cdb-snapp
      - sensenet__apikeys__healthcheckeruser=s3Cur3P4Ss
      - sensenet__authentication__authority=https://localhost:51017
      - sensenet__authentication__repositoryUrl=https://localhost:51016
      - sensenet__authentication__authServerType=IdentityServer
      - sensenet__authentication__AddJwtCookie=true
      - sensenet__identityManagement__UserProfilesEnabled=false
      - ConnectionStrings__SnCrMsSql=Persist Security Info=False;Initial Catalog=sensenet-insql-cdb-sndb;Data Source=sensenet-insql-cdb-snsql;User ID=sa;Password=SuP3rS3CuR3P4sSw0Rd;TrustServerCertificate=true
      - sensenet__authentication__metadatahost=http://sensenet-insql-cdb-snis
      - Kestrel__Certificates__Default__Path=/root/.aspnet/https/snapp.pfx
      - Kestrel__Certificates__Default__Password=SuP3rS3CuR3P4sSw0Rd
    volumes:
      - ./temp/certificates:/root/.aspnet/https:ro
      - ./volumes:/app/App_Data
    ports:
      - "51016:443"
    restart: always

networks:
  snnetwork:
    driver: bridge
