using System;
using System.Collections.Generic;
using System.Linq;

namespace SenseNet.ContentRepository.Storage
{
	public static class MimeTable
	{
		private static readonly string[] DefaultMimeTypes;
		private static readonly Dictionary<string, string[]> MimeByExtension;
	    private static readonly string[] CompressedTypes;
        private static readonly string[] FontTypes;

        public static string DefaultMimeType => DefaultMimeTypes[0];

	    static MimeTable()
		{
			DefaultMimeTypes = new[] { "application/octet-stream" };
            CompressedTypes = new[] { "svgz" };
            FontTypes = new[] { "ttf", "woff", "eot", "svg" };

		    MimeByExtension = new Dictionary<string, string[]>
		    {
		        {"content", new[] {"text/xml"}},
		        {"contenttype", new[] {"text/xml"}},
		        {"3dm", new[] {"x-world/x-3dmf"}},
		        {"3dmf", new[] {"x-world/x-3dmf"}},
		        {"a", new[] {"application/octet-stream"}},
		        {"aab", new[] {"application/x-authorware-bin"}},
		        {"aam", new[] {"application/x-authorware-map"}},
		        {"aas", new[] {"application/x-authorware-seg"}},
		        {"abc", new[] {"text/vnd.abc"}},
		        {"acgi", new[] {"text/html"}},
		        {"afl", new[] {"video/animaflex"}},
		        {"ai", new[] {"application/postscript"}},
		        {"aif", new[] {"audio/aiff", "audio/x-aiff"}},
		        {"aifc", new[] {"audio/aiff", "audio/x-aiff"}},
		        {"aiff", new[] {"audio/aiff", "audio/x-aiff"}},
		        {"aim", new[] {"application/x-aim"}},
		        {"aip", new[] {"text/x-audiosoft-intra"}},
		        {"ani", new[] {"application/x-navi-animation"}},
		        {"aos", new[] {"application/x-nokia-9000-communicator-add-on-software"}},
		        {"aps", new[] {"application/mime"}},
		        {"arc", new[] {"application/octet-stream"}},
		        {"arj", new[] {"application/arj", "application/octet-stream"}},
		        {"art", new[] {"image/x-jg"}},
		        {"ascx", new[] {"text/asp"}},
		        {"asf", new[] {"video/x-ms-asf"}},
		        {"asm", new[] {"text/x-asm"}},
		        {"asp", new[] {"text/asp"}},
		        {"aspx", new[] {"text/asp"}},
		        {"asx", new[] {"video/x-ms-asf", "video/x-ms-asf-plugin", "application/x-mplayer2"}},
		        {"au", new[] {"audio/x-au", "audio/basic"}},
		        {"avi", new[] {"video/avi", "video/msvideo", "video/x-msvideo", "application/x-troff-msvideo"}},
		        {"avs", new[] {"video/avs-video"}},
		        {"bcpio", new[] {"application/x-bcpio"}},
		        {
		            "bin",
		            new[]
		            {
		                "application/octet-stream", "application/x-binary", "application/mac-binary", "application/macbinary",
		                "application/x-macbinary"
		            }
		        },
		        {"bm", new[] {"image/bmp"}},
		        {"bmp", new[] {"image/bmp", "image/x-windows-bmp"}},
		        {"boo", new[] {"application/book"}},
		        {"book", new[] {"application/book"}},
		        {"boz", new[] {"application/x-bzip2"}},
		        {"bsh", new[] {"application/x-bsh"}},
		        {"bz", new[] {"application/x-bzip"}},
		        {"bz2", new[] {"application/x-bzip2"}},
		        {"c", new[] {"text/x-c", "text/plain"}},
		        {"c++", new[] {"text/plain"}},
		        {"cat", new[] {"application/vnd.ms-pki.seccat"}},
		        {"cc", new[] {"text/plain", "text/x-c"}},
		        {"ccad", new[] {"application/clariscad"}},
		        {"cco", new[] {"application/x-cocoa"}},
		        {"cdf", new[] {"application/cdf", "application/x-cdf", "application/x-netcdf"}},
		        {"cer", new[] {"application/pkix-cert", "application/x-x509-ca-cert"}},
		        {"cha", new[] {"application/x-chat"}},
		        {"chat", new[] {"application/x-chat"}},
		        {"class", new[] {"application/java", "application/java-byte-code", "application/x-java-class"}},
		        {"com", new[] {"text/plain", "application/octet-stream"}},
		        {"conf", new[] {"text/plain"}},
		        {"cpio", new[] {"application/x-cpio"}},
		        {"cpp", new[] {"text/x-c"}},
		        {"cpt", new[] {"application/x-cpt", "application/x-compactpro", "application/mac-compactpro"}},
		        {"crl", new[] {"application/pkcs-crl", "application/pkix-crl"}},
		        {"crt", new[] {"application/pkix-cert", "application/x-x509-ca-cert", "application/x-x509-user-cert"}},
		        {"csh", new[] {"application/x-csh", "text/x-script.csh"}},
		        {"css", new[] {"text/css", "application/x-pointplus"}},
		        {"cxx", new[] {"text/plain"}},
		        {"dcr", new[] {"application/x-director"}},
		        {"deepv", new[] {"application/x-deepv"}},
		        {"def", new[] {"text/plain"}},
		        {"der", new[] {"application/x-x509-ca-cert"}},
		        {"dif", new[] {"video/x-dv"}},
		        {"dir", new[] {"application/x-director"}},
		        {"dl", new[] {"video/dl", "video/x-dl"}},
		        {"doc", new[] {"application/msword"}},
		        {"docx", new[] {"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}},
		        {"dotx", new[] {"application/vnd.openxmlformats-officedocument.wordprocessingml.template"}},
		        {"dot", new[] {"application/msword"}},
		        {"dp", new[] {"application/commonground"}},
		        {"drw", new[] {"application/drafting"}},
		        {"dump", new[] {"application/octet-stream"}},
		        {"dv", new[] {"video/x-dv"}},
		        {"dvi", new[] {"application/x-dvi"}},
		        {"dwf", new[] {"drawing/x-dwf", "model/vnd.dwf"}},
		        {"dwg", new[] {"image/x-dwg", "application/acad", "image/vnd.dwg"}},
		        {"dxf", new[] {"image/vnd.dwg", "image/x-dwg", "application/dxf"}},
		        {"dxr", new[] {"application/x-director"}},
		        {"el", new[] {"text/x-script.elisp"}},
		        {"elc", new[] {"application/x-elc", "application/x-bytecode.elisp"}},
		        {"env", new[] {"application/x-envoy"}},
		        {"eot", new[] {"application/vnd.ms-fontobject"}},
		        {"eps", new[] {"application/postscript"}},
		        {"es", new[] {"application/x-esrehber"}},
		        {"etx", new[] {"text/x-setext"}},
		        {"evy", new[] {"application/envoy", "application/x-envoy"}},
		        {"exe", new[] {"application/octet-stream"}},
		        {"f", new[] {"text/plain", "text/x-fortran"}},
		        {"f77", new[] {"text/x-fortran"}},
		        {"f90", new[] {"text/plain", "text/x-fortran"}},
		        {"fdf", new[] {"application/vnd.fdf"}},
		        {"fif", new[] {"image/fif", "application/fractals"}},
		        {"fli", new[] {"video/fli", "video/x-fli"}},
		        {"flo", new[] {"image/florian"}},
		        {"flx", new[] {"text/vnd.fmi.flexstor"}},
		        {"fmf", new[] {"video/x-atomic3d-feature"}},
		        {"for", new[] {"text/plain", "text/x-fortran"}},
		        {"fpx", new[] {"image/vnd.fpx", "image/vnd.net-fpx"}},
		        {"frl", new[] {"application/freeloader"}},
		        {"funk", new[] {"audio/make"}},
		        {"g", new[] {"text/plain"}},
		        {"g3", new[] {"image/g3fax"}},
		        {"gif", new[] {"image/gif"}},
		        {"gl", new[] {"video/gl", "video/x-gl"}},
		        {"gsd", new[] {"audio/x-gsm"}},
		        {"gsm", new[] {"audio/x-gsm"}},
		        {"gsp", new[] {"application/x-gsp"}},
		        {"gss", new[] {"application/x-gss"}},
		        {"gtar", new[] {"application/x-gtar"}},
		        {"gz", new[] {"application/x-gzip", "application/x-compressed"}},
		        {"gzip", new[] {"application/x-gzip", "multipart/x-gzip"}},
		        {"h", new[] {"text/plain", "text/x-h"}},
		        {"hdf", new[] {"application/x-hdf"}},
		        {"help", new[] {"application/x-helpfile"}},
		        {"hgl", new[] {"application/vnd.hp-hpgl"}},
		        {"hh", new[] {"text/plain", "text/x-h"}},
		        {"hlb", new[] {"text/x-script"}},
		        {"hlp", new[] {"application/hlp", "application/x-helpfile", "application/x-winhelp"}},
		        {"hpg", new[] {"application/vnd.hp-hpgl"}},
		        {"hpgl", new[] {"application/vnd.hp-hpgl"}},
		        {
		            "hqx",
		            new[]
		            {
		                "application/binhex", "application/binhex4", "application/mac-binhex", "application/mac-binhex40",
		                "application/x-binhex40", "application/x-mac-binhex40"
		            }
		        },
		        {"hta", new[] {"application/hta"}},
		        {"htc", new[] {"text/x-component"}},
		        {"htm", new[] {"text/html"}},
		        {"html", new[] {"text/html"}},
		        {"htmls", new[] {"text/html"}},
		        {"htt", new[] {"text/webviewhtml"}},
		        {"htx", new[] {"text/html"}},
		        {"ice", new[] {"x-conference/x-cooltalk"}},
		        {"ico", new[] {"image/x-icon"}},
		        {"idc", new[] {"text/plain"}},
		        {"ief", new[] {"image/ief"}},
		        {"iefs", new[] {"image/ief"}},
		        {"iges", new[] {"application/iges", "model/iges"}},
		        {"igs", new[] {"model/iges", "application/iges"}},
		        {"ima", new[] {"application/x-ima"}},
		        {"imap", new[] {"application/x-httpd-imap"}},
		        {"inf", new[] {"application/inf"}},
		        {"ins", new[] {"application/x-internett-signup"}},
		        {"ip", new[] {"application/x-ip2"}},
		        {"isu", new[] {"video/x-isvideo"}},
		        {"it", new[] {"audio/it"}},
		        {"iv", new[] {"application/x-inventor"}},
		        {"ivr", new[] {"i-world/i-vrml"}},
		        {"ivy", new[] {"application/x-livescreen"}},
		        {"jam", new[] {"audio/x-jam"}},
		        {"jav", new[] {"text/plain", "text/x-java-source"}},
		        {"java", new[] {"text/plain", "text/x-java-source"}},
		        {"jcm", new[] {"application/x-java-commerce"}},
		        {"jfif", new[] {"image/jpeg", "image/pjpeg"}},
		        {"jfif-tbnl", new[] {"image/jpeg"}},
		        {"jpe", new[] {"image/jpeg", "image/pjpeg"}},
		        {"jpeg", new[] {"image/jpeg", "image/pjpeg"}},
		        {"jpg", new[] {"image/jpeg", "image/pjpeg"}},
		        {"jps", new[] {"image/x-jps"}},
		        {"js", new[] {"application/x-javascript"}},
		        {"jut", new[] {"image/jutvision"}},
		        {"kar", new[] {"audio/midi", "music/x-karaoke"}},
		        {"ksh", new[] {"application/x-ksh", "text/x-script.ksh"}},
		        {"la", new[] {"audio/nspaudio", "audio/x-nspaudio"}},
		        {"lam", new[] {"audio/x-liveaudio"}},
		        {"latex", new[] {"application/x-latex"}},
		        {"lha", new[] {"application/lha", "application/octet-stream", "application/x-lha"}},
		        {"lhx", new[] {"application/octet-stream"}},
		        {"list", new[] {"text/plain"}},
		        {"lma", new[] {"audio/nspaudio", "audio/x-nspaudio"}},
		        {"log", new[] {"text/plain"}},
		        {"lsp", new[] {"application/x-lisp", "text/x-script.lisp"}},
		        {"lst", new[] {"text/plain"}},
		        {"lsx", new[] {"text/x-la-asf"}},
		        {"ltx", new[] {"application/x-latex"}},
		        {"lzh", new[] {"application/x-lzh", "application/octet-stream"}},
		        {"lzx", new[] {"application/lzx", "application/octet-stream", "application/x-lzx"}},
		        {"m", new[] {"text/plain", "text/x-m"}},
		        {"m1v", new[] {"video/mpeg"}},
		        {"m2a", new[] {"audio/mpeg"}},
		        {"m2v", new[] {"video/mpeg"}},
		        {"m3u", new[] {"audio/x-mpequrl"}},
		        {"man", new[] {"application/x-troff-man"}},
		        {"map", new[] {"application/x-navimap"}},
		        {"mar", new[] {"text/plain"}},
		        {"mbd", new[] {"application/mbedlet"}},
		        {"mc$", new[] {"application/x-magic-cap-package-1.0"}},
		        {"mcd", new[] {"application/mcad", "application/x-mathcad"}},
		        {"mcf", new[] {"text/mcf", "image/vasa"}},
		        {"mcp", new[] {"application/netmc"}},
		        {"me", new[] {"application/x-troff-me"}},
		        {"mht", new[] {"message/rfc822"}},
		        {"mhtml", new[] {"message/rfc822"}},
		        {
		            "mid",
		            new[]
		            {
		                "audio/midi", "application/x-midi", "audio/x-mid", "audio/x-midi", "music/crescendo", "x-music/x-midi"
		            }
		        },
		        {
		            "midi",
		            new[]
		            {
		                "audio/midi", "application/x-midi", "audio/x-mid", "audio/x-midi", "music/crescendo", "x-music/x-midi"
		            }
		        },
		        {"mif", new[] {"application/x-mif", "application/x-frame"}},
		        {"mime", new[] {"www/mime", "message/rfc822"}},
		        {"mjf", new[] {"audio/x-vnd.audioexplosion.mjuicemediafile"}},
		        {"mjpg", new[] {"video/x-motion-jpeg"}},
		        {"mm", new[] {"application/base64", "application/x-meme"}},
		        {"mme", new[] {"application/base64"}},
		        {"mod", new[] {"audio/mod", "audio/x-mod"}},
		        {"moov", new[] {"video/quicktime"}},
		        {"mov", new[] {"video/quicktime"}},
		        {"movie", new[] {"video/x-sgi-movie"}},
		        {"mp2", new[] {"audio/mpeg", "audio/x-mpeg", "video/mpeg", "video/x-mpeg", "video/x-mpeq2a"}},
		        {"mp3", new[] {"video/mpeg", "audio/mpeg3", "audio/x-mpeg-3", "video/x-mpeg"}},
		        {"mpa", new[] {"audio/mpeg", "video/mpeg"}},
		        {"mpc", new[] {"application/x-project"}},
		        {"mpe", new[] {"video/mpeg"}},
		        {"mpeg", new[] {"video/mpeg"}},
		        {"mpg", new[] {"video/mpeg", "audio/mpeg"}},
		        {"mpga", new[] {"audio/mpeg"}},
		        {"mpp", new[] {"application/vnd.ms-project"}},
		        {"mpt", new[] {"application/x-project"}},
		        {"mpv", new[] {"application/x-project"}},
		        {"mpx", new[] {"application/x-project"}},
		        {"mrc", new[] {"application/marc"}},
		        {"ms", new[] {"application/x-troff-ms"}},
		        {"mv", new[] {"video/x-sgi-movie"}},
		        {"my", new[] {"audio/make"}},
		        {"mzz", new[] {"application/x-vnd.audioexplosion.mzz"}},
		        {"nap", new[] {"image/naplps"}},
		        {"naplps", new[] {"image/naplps"}},
		        {"nc", new[] {"application/x-netcdf"}},
		        {"ncm", new[] {"application/vnd.nokia.configuration-message"}},
		        {"nif", new[] {"image/x-niff"}},
		        {"niff", new[] {"image/x-niff"}},
		        {"nix", new[] {"application/x-mix-transfer"}},
		        {"nsc", new[] {"application/x-conference"}},
		        {"nvd", new[] {"application/x-navidoc"}},
		        {"o", new[] {"application/octet-stream"}},
		        {"oda", new[] {"application/oda"}},
		        {"omc", new[] {"application/x-omc"}},
		        {"omcd", new[] {"application/x-omcdatamaker"}},
		        {"omcr", new[] {"application/x-omcregerator"}},
		        {"otf", new[] {"font/opentype"}},
		        {"p", new[] {"text/x-pascal"}},
		        {"p10", new[] {"application/pkcs10", "application/x-pkcs10"}},
		        {"p12", new[] {"application/pkcs-12", "application/x-pkcs12"}},
		        {"p7a", new[] {"application/x-pkcs7-signature"}},
		        {"p7c", new[] {"application/pkcs7-mime", "application/x-pkcs7-mime"}},
		        {"p7m", new[] {"application/pkcs7-mime", "application/x-pkcs7-mime"}},
		        {"p7r", new[] {"application/x-pkcs7-certreqresp"}},
		        {"p7s", new[] {"application/pkcs7-signature"}},
		        {"part", new[] {"application/pro_eng"}},
		        {"pas", new[] {"text/pascal"}},
		        {"pbm", new[] {"image/x-portable-bitmap"}},
		        {"pcl", new[] {"application/vnd.hp-pcl", "application/x-pcl"}},
		        {"pct", new[] {"image/x-pict"}},
		        {"pcx", new[] {"image/x-pcx"}},
		        {"pdb", new[] {"chemical/x-pdb"}},
		        {"pdf", new[] {"application/pdf"}},
		        {"pfunk", new[] {"audio/make", "audio/make.my.funk"}},
		        {"pgm", new[] {"image/x-portable-graymap", "image/x-portable-greymap"}},
		        {"pic", new[] {"image/pict"}},
		        {"pict", new[] {"image/pict"}},
		        {"pkg", new[] {"application/x-newton-compatible-pkg"}},
		        {"pko", new[] {"application/vnd.ms-pki.pko"}},
		        {"pl", new[] {"text/plain", "text/x-script.perl"}},
		        {"plx", new[] {"application/x-pixclscript"}},
		        {"pm", new[] {"image/x-xpixmap", "text/x-script.perl-module"}},
		        {"pm4", new[] {"application/x-pagemaker"}},
		        {"pm5", new[] {"application/x-pagemaker"}},
		        {"png", new[] {"image/png"}},
		        {"pnm", new[] {"application/x-portable-anymap", "image/x-portable-anymap"}},
		        {"pot", new[] {"application/vnd.ms-powerpoint", "application/mspowerpoint"}},
		        {"pov", new[] {"model/x-pov"}},
		        {"ppa", new[] {"application/vnd.ms-powerpoint"}},
		        {"ppm", new[] {"image/x-portable-pixmap"}},
		        {"pps", new[] {"application/vnd.ms-powerpoint", "application/mspowerpoint"}},
		        {
		            "ppt",
		            new[]
		            {
		                "application/vnd.ms-powerpoint", "application/powerpoint", "application/mspowerpoint",
		                "application/x-mspowerpoint"
		            }
		        },
		        {"pptx", new[] {"application/vnd.openxmlformats-officedocument.presentationml.presentation"}},
		        {"ppz", new[] {"application/mspowerpoint"}},
		        {"pre", new[] {"application/x-freelance"}},
		        {"prt", new[] {"application/pro_eng"}},
		        {"ps", new[] {"application/postscript"}},
		        {"psd", new[] {"application/octet-stream"}},
		        {"pvu", new[] {"paleovu/x-pv"}},
		        {"pwz", new[] {"application/vnd.ms-powerpoint"}},
		        {"py", new[] {"text/x-script.phyton"}},
		        {"pyc", new[] {"applicaiton/x-bytecode.python"}},
		        {"qcp", new[] {"audio/vnd.qcelp"}},
		        {"qd3", new[] {"x-world/x-3dmf"}},
		        {"qd3d", new[] {"x-world/x-3dmf"}},
		        {"qif", new[] {"image/x-quicktime"}},
		        {"qt", new[] {"video/quicktime"}},
		        {"qtc", new[] {"video/x-qtc"}},
		        {"qti", new[] {"image/x-quicktime"}},
		        {"qtif", new[] {"image/x-quicktime"}},
		        {"ra", new[] {"audio/x-pn-realaudio", "audio/x-pn-realaudio-plugin", "audio/x-realaudio"}},
		        {"ram", new[] {"audio/x-pn-realaudio"}},
		        {"ras", new[] {"image/cmu-raster", "image/x-cmu-raster", "application/x-cmu-raster"}},
		        {"rast", new[] {"image/cmu-raster"}},
		        {"rexx", new[] {"text/x-script.rexx"}},
		        {"rf", new[] {"image/vnd.rn-realflash"}},
		        {"rgb", new[] {"image/x-rgb"}},
		        {"rm", new[] {"application/vnd.rn-realmedia", "audio/x-pn-realaudio"}},
		        {"rmi", new[] {"audio/mid"}},
		        {"rmm", new[] {"audio/x-pn-realaudio"}},
		        {"rmp", new[] {"audio/x-pn-realaudio", "audio/x-pn-realaudio-plugin"}},
		        {"rng", new[] {"application/vnd.nokia.ringing-tone", "application/ringing-tones"}},
		        {"rnx", new[] {"application/vnd.rn-realplayer"}},
		        {"roff", new[] {"application/x-troff"}},
		        {"rp", new[] {"image/vnd.rn-realpix"}},
		        {"rpm", new[] {"audio/x-pn-realaudio-plugin"}},
		        {"rt", new[] {"text/richtext", "text/vnd.rn-realtext"}},
		        {"rtf", new[] {"text/richtext", "application/rtf", "application/x-rtf"}},
		        {"rtx", new[] {"text/richtext", "application/rtf"}},
		        {"rv", new[] {"video/vnd.rn-realvideo"}},
		        {"s", new[] {"text/x-asm"}},
		        {"s3m", new[] {"audio/s3m"}},
		        {"saveme", new[] {"application/octet-stream"}},
		        {"sbk", new[] {"application/x-tbook"}},
		        {
		            "scm",
		            new[]
		                {"application/x-lotusscreencam", "text/x-script.guile", "text/x-script.scheme", "video/x-scm"}
		        },
		        {"sdml", new[] {"text/plain"}},
		        {"sdp", new[] {"application/sdp", "application/x-sdp"}},
		        {"sdr", new[] {"application/sounder"}},
		        {"sea", new[] {"application/sea", "application/x-sea"}},
		        {"set", new[] {"application/set"}},
		        {"sgm", new[] {"text/sgml", "text/x-sgml"}},
		        {"sgml", new[] {"text/sgml", "text/x-sgml"}},
		        {"sh", new[] {"application/x-sh", "application/x-bsh", "application/x-shar", "text/x-script.sh"}},
		        {"shar", new[] {"application/x-bsh", "application/x-shar"}},
		        {"shtml", new[] {"text/html", "text/x-server-parsed-html"}},
		        {"sid", new[] {"audio/x-psid"}},
		        {"sit", new[] {"application/x-sit", "application/x-stuffit"}},
		        {"skd", new[] {"application/x-koan"}},
		        {"skm", new[] {"application/x-koan"}},
		        {"skp", new[] {"application/x-koan"}},
		        {"skt", new[] {"application/x-koan"}},
		        {"sl", new[] {"application/x-seelogo"}},
		        {"smi", new[] {"application/smil"}},
		        {"smil", new[] {"application/smil"}},
		        {"snd", new[] {"audio/basic", "audio/x-adpcm"}},
		        {"sol", new[] {"application/solids"}},
		        {"spc", new[] {"text/x-speech", "application/x-pkcs7-certificates"}},
		        {"spl", new[] {"application/futuresplash"}},
		        {"spr", new[] {"application/x-sprite"}},
		        {"sprite", new[] {"application/x-sprite"}},
		        {"src", new[] {"application/x-wais-source"}},
		        {"ssi", new[] {"text/x-server-parsed-html"}},
		        {"ssm", new[] {"application/streamingmedia"}},
		        {"sst", new[] {"application/vnd.ms-pki.certstore"}},
		        {"step", new[] {"application/step"}},
		        {"stl", new[] {"application/vnd.ms-pki.stl", "application/sla", "application/x-navistyle"}},
		        {"stp", new[] {"application/step"}},
		        {"sv4cpio", new[] {"application/x-sv4cpio"}},
		        {"sv4crc", new[] {"application/x-sv4crc"}},
		        {"svf", new[] {"image/vnd.dwg", "image/x-dwg"}},
		        {"svg", new[] {"image/svg+xml"}},
		        {"svgz", new[] {"image/svg+xml"}},
		        {"svr", new[] {"application/x-world", "x-world/x-svr"}},
		        {"swf", new[] {"application/x-shockwave-flash"}},
		        {"t", new[] {"application/x-troff"}},
		        {"talk", new[] {"text/x-speech"}},
		        {"tar", new[] {"application/x-tar"}},
		        {"tbk", new[] {"application/toolbook", "application/x-tbook"}},
		        {"tcl", new[] {"application/x-tcl", "text/x-script.tcl"}},
		        {"tcsh", new[] {"text/x-script.tcsh"}},
		        {"tex", new[] {"application/x-tex"}},
		        {"texi", new[] {"application/x-texinfo"}},
		        {"texinfo", new[] {"application/x-texinfo"}},
		        {"text", new[] {"text/plain", "application/plain"}},
		        {"tgz", new[] {"application/x-compressed", "application/gnutar"}},
		        {"tif", new[] {"image/tiff", "image/x-tiff"}},
		        {"tiff", new[] {"image/tiff", "image/x-tiff"}},
		        {"tr", new[] {"application/x-troff"}},
		        {"tsi", new[] {"audio/tsp-audio"}},
		        {"tsp", new[] {"application/dsptype", "audio/tsplayer"}},
		        {"tsv", new[] {"text/tab-separated-values"}},
		        {"ttf", new[] {"application/x-font-ttf"}},
		        {"turbot", new[] {"image/florian"}},
		        {"txt", new[] {"text/plain"}},
		        {"uil", new[] {"text/x-uil"}},
		        {"uni", new[] {"text/uri-list"}},
		        {"unis", new[] {"text/uri-list"}},
		        {"unv", new[] {"application/i-deas"}},
		        {"uri", new[] {"text/uri-list"}},
		        {"uris", new[] {"text/uri-list"}},
		        {"ustar", new[] {"multipart/x-ustar", "application/x-ustar"}},
		        {"uu", new[] {"text/x-uuencode", "application/octet-stream"}},
		        {"uue", new[] {"text/x-uuencode"}},
		        {"vcd", new[] {"application/x-cdlink"}},
		        {"vcs", new[] {"text/x-vcalendar"}},
		        {"vda", new[] {"application/vda"}},
		        {"vdo", new[] {"video/vdo"}},
		        {"vew", new[] {"application/groupwise"}},
		        {"viv", new[] {"video/vivo", "video/vnd.vivo"}},
		        {"vivo", new[] {"video/vivo", "video/vnd.vivo"}},
		        {"vmd", new[] {"application/vocaltec-media-desc"}},
		        {"vmf", new[] {"application/vocaltec-media-file"}},
		        {"voc", new[] {"audio/voc", "audio/x-voc"}},
		        {"vos", new[] {"video/vosaic"}},
		        {"vox", new[] {"audio/voxware"}},
		        {"vqe", new[] {"audio/x-twinvq-plugin"}},
		        {"vqf", new[] {"audio/x-twinvq"}},
		        {"vql", new[] {"audio/x-twinvq-plugin"}},
		        {"vrml", new[] {"model/vrml", "application/x-vrml", "x-world/x-vrml"}},
		        {"vrt", new[] {"x-world/x-vrt"}},
		        {"vsd", new[] {"application/x-visio"}},
		        {"vst", new[] {"application/x-visio"}},
		        {"vsw", new[] {"application/x-visio"}},
		        {"w60", new[] {"application/wordperfect6.0"}},
		        {"w61", new[] {"application/wordperfect6.1"}},
		        {"w6w", new[] {"application/msword"}},
		        {"wav", new[] {"audio/wav", "audio/x-wav"}},
		        {"wb1", new[] {"application/x-qpro"}},
		        {"wbmp", new[] {"image/vnd.wap.wbmp"}},
		        {"web", new[] {"application/vnd.xara"}},
		        {"wiz", new[] {"application/msword"}},
		        {"wk1", new[] {"application/x-123"}},
		        {"wmf", new[] {"windows/metafile"}},
		        {"wml", new[] {"text/vnd.wap.wml"}},
		        {"wmlc", new[] {"application/vnd.wap.wmlc"}},
		        {"wmls", new[] {"text/vnd.wap.wmlscript"}},
		        {"wmlsc", new[] {"application/vnd.wap.wmlscriptc"}},
		        {"woff", new[] {"application/x-font-woff"}},
		        {"word", new[] {"application/msword"}},
		        {"wp", new[] {"application/wordperfect"}},
		        {"wp5", new[] {"application/wordperfect"}},
		        {"wp6", new[] {"application/wordperfect"}},
		        {"wpd", new[] {"application/wordperfect", "application/x-wpwin"}},
		        {"wq1", new[] {"application/x-lotus"}},
		        {"wri", new[] {"application/mswrite", "application/x-wri"}},
		        {"wrl", new[] {"model/vrml", "application/x-world", "x-world/x-vrml"}},
		        {"wrz", new[] {"model/vrml", "x-world/x-vrml"}},
		        {"wsc", new[] {"text/scriplet"}},
		        {"wsrc", new[] {"application/x-wais-source"}},
		        {"wtk", new[] {"application/x-wintalk"}},
		        {"xbm", new[] {"image/xbm", "image/x-xbitmap", "image/x-xbm"}},
		        {"xdr", new[] {"video/x-amt-demorun"}},
		        {"xgz", new[] {"xgl/drawing"}},
		        {"xif", new[] {"image/vnd.xiff"}},
		        {"xl", new[] {"application/excel"}},
		        {"xla", new[] {"application/excel", "application/x-excel", "application/x-msexcel"}},
		        {"xlb", new[] {"application/vnd.ms-excel", "application/excel", "application/x-excel"}},
		        {"xlc", new[] {"application/vnd.ms-excel", "application/excel", "application/x-excel"}},
		        {"xld", new[] {"application/excel", "application/x-excel"}},
		        {"xlk", new[] {"application/excel", "application/x-excel"}},
		        {"xll", new[] {"application/vnd.ms-excel", "application/excel", "application/x-excel"}},
		        {"xlm", new[] {"application/vnd.ms-excel", "application/excel", "application/x-excel"}},
		        {
		            "xls",
		            new[]
		                {"application/vnd.ms-excel", "application/excel", "application/x-excel", "application/x-msexcel"}
		        },
		        {"xlsx", new[] {"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}},
		        {"xltx", new[] {"application/vnd.openxmlformats-officedocument.spreadsheetml.template"}},
		        {"xlt", new[] {"application/excel", "application/x-excel"}},
		        {"xlv", new[] {"application/excel", "application/x-excel"}},
		        {
		            "xlw",
		            new[]
		                {"application/vnd.ms-excel", "application/excel", "application/x-excel", "application/x-msexcel"}
		        },
		        {"xm", new[] {"audio/xm"}},
		        {"xml", new[] {"text/xml", "application/xml"}},
		        {"xmz", new[] {"xgl/movie"}},
		        {"xpix", new[] {"application/x-vnd.ls-xpix"}},
		        {"xpm", new[] {"image/xpm", "image/x-xpixmap"}},
		        {"x-png", new[] {"image/png"}},
		        {"xsr", new[] {"video/x-amt-showrun"}},
		        {"xwd", new[] {"image/x-xwd", "image/x-xwindowdump"}},
		        {"xyz", new[] {"chemical/x-pdb"}},
		        {"z", new[] {"application/x-compressed", "application/x-compress"}},
		        {
		            "zip",
		            new[]
		                {"application/zip", "application/x-compressed", "application/x-zip-compressed", "multipart/x-zip"}
		        },
		        {"zoo", new[] {"application/octet-stream"}},
		        {"zsh", new[] {"text/x-script.zsh"}}
		    };


		}

		public static string[] GetKnownExtensions()
		{
			string[] keys = new string[MimeByExtension.Count];
			MimeByExtension.Keys.CopyTo(keys, 0);
			return keys;
		}
        public static string[] GetMimeTypes(string fileExtension)
		{
		    return MimeByExtension.TryGetValue(GetPureExtension(fileExtension), out var mimes) ? mimes : DefaultMimeTypes;
		}
        public static string GetMimeType(string fileExtension)
		{
			return GetMimeTypes(fileExtension)[0];
		}
        public static bool IsCompressedType(string fileExtension)
        {
            return CompressedTypes.Contains(GetPureExtension(fileExtension));
        }

        public static bool IsFontType(string fileExtension)
        {
            return FontTypes.Contains(GetPureExtension(fileExtension));
        }

        private static string GetPureExtension(string fileExtension)
        {
            if (string.IsNullOrEmpty(fileExtension))
                return fileExtension;

            return fileExtension.StartsWith(".", StringComparison.Ordinal) ? fileExtension.Substring(1) : fileExtension;
        }
	}
}
